name: CI Preview Deployment

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            pnpm install --no-frozen-lockfile
          else
            pnpm install
          fi

      - name: Build and deploy preview
        run: pnpm run build
